Master tasting admin
askaret/beertasting-blazor pull request #8
Opened 2021-09-27 21:17 UTC by lowren

Closes #4

2021-09-28 21:31 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +<EditForm Model="@tasting">
Add onValidSubmit

2021-09-28 21:34 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +<EditForm Model="@tasting">
Done

2021-09-29 07:54 UTC, askaret requested changes

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +
Add headings? h3 Tasting, h4 Edit

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +                        <MudIconButton Icon="@Icons.Material.Outlined.ArrowUpward" Color="Color.Primary" Size="Size.Small" Variant="Variant.Outlined" OnClick="@(() => SwitchBeerSortOrder(tbContext.So
It would be prettier with an enum SortOrderChange { Up, Down }
Parameters could then just be tbContext, SortOrderChange.Up / Down

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +                    <MudTd DataLabel="Ratebeer">
We have used URL and Ratebeer in different places, standardize on something? URL is shorter...perhaps change Ratebeer to URL?

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +    private async void SwitchBeerSortOrder(int sortOrder, int otherSortOrder)
See previous comment, requires rewrite if we go the Enum-route

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Tasting.razor
> +
Heading h4 New Tasting

2021-09-29 07:54 UTC, askaret commented on BlazorTest/Pages/admin/tasting/Tasting.razor
> +
Heading h4 All tastings

2021-09-29 07:54 UTC, askaret commented on BlazorTest/ViewModels/TastingViewModel.cs
> +        {
if (other is null) return false;

2021-09-29 14:19 UTC, lowren commented on BlazorTest/ViewModels/TastingViewModel.cs
> +        {
Don't think this is used, should be deleted

2021-09-29 15:59 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +
Done

2021-09-29 16:08 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +                        <MudIconButton Icon="@Icons.Material.Outlined.ArrowUpward" Color="Color.Primary" Size="Size.Small" Variant="Variant.Outlined" OnClick="@(() => SwitchBeerSortOrder(tbContext.So
Done

2021-09-29 16:09 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +                    <MudTd DataLabel="Ratebeer">
Changed to URL

2021-09-29 16:12 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Edit.razor
> +    private async void SwitchBeerSortOrder(int sortOrder, int otherSortOrder)
Done

2021-09-29 16:13 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Tasting.razor
> +
Done

2021-09-29 16:15 UTC, lowren commented on BlazorTest/Pages/admin/tasting/Tasting.razor
> +
Header in ToolBarContent, same as for beer. Letting it be for now, but changed from h6 to h4

2021-09-29 16:16 UTC, lowren commented on BlazorTest/ViewModels/TastingViewModel.cs
> +        {
Removed

2021-09-29 20:07 UTC, askaret approved these changes

2021-09-29 20:07 UTC, merged